# Generated by Django 4.0.4 on 2022-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='Phone Number')),
                ('roll_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Roll Number')),
                ('application_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Registration Number')),
                ('uid', models.CharField(max_length=20, null=True, verbose_name='UID')),
                ('section', models.CharField(max_length=20, null=True, verbose_name='Section')),
                ('dob', models.DateField(max_length=20, null=True, verbose_name='Date Of Birth')),
                ('course', models.CharField(max_length=200, null=True, verbose_name='Course')),
                ('admitted_through', models.CharField(max_length=200, null=True, verbose_name='Admitted Through')),
                ('applied_year', models.CharField(max_length=20, null=True, verbose_name='Applied Year')),
                ('address', models.CharField(max_length=500, null=True, verbose_name='address')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='city')),
                ('state', models.CharField(max_length=200, null=True, verbose_name='state')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='country')),
                ('alternate_address', models.CharField(max_length=500, null=True, verbose_name='alternate_address')),
                ('house_number', models.CharField(max_length=5, null=True, verbose_name='house_number')),
                ('pincode', models.CharField(max_length=10, null=True, verbose_name='pincode')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
