# Generated by Django 4.0.4 on 2022-05-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='Phone Number')),
                ('roll_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Roll Number')),
                ('university_mail_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='University Mail Id')),
                ('school', models.CharField(choices=[('None', 'None'), ('School Of Engineering', 'School Of Engineering'), ('School Of Law', 'School Of Law'), ('School Of Desiging', 'School Of Desiging'), ('School Of Management', 'School Of Management')], default='None', max_length=100, verbose_name='School')),
                ('section', models.CharField(max_length=20, verbose_name='Section')),
                ('dob', models.DateField(max_length=20, null=True, verbose_name='Date Of Birth')),
                ('course', models.CharField(max_length=50, null=True, verbose_name='Course')),
                ('ambition', models.CharField(max_length=1500, null=True, verbose_name='Ambition')),
                ('semester', models.CharField(max_length=20, null=True, verbose_name='Semester')),
                ('permanent_address', models.CharField(max_length=600, null=True, verbose_name='Permanent Address')),
                ('gender', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='None', max_length=20, verbose_name='Gender')),
                ('hobbies', models.CharField(max_length=500, null=True, verbose_name='hobbies')),
                ('current_address', models.CharField(max_length=600, null=True, verbose_name='Current Address')),
            ],
        ),
    ]
