# Generated by Django 4.0.4 on 2022-05-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_stu_register_why_ccagc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_register',
            name='barries',
            field=models.TextField(max_length=5000, null=True, verbose_name='What kinds of barriers do you think could get in the way of you pursuing the career you want, or meeting your career goals?'),
        ),
        migrations.AddField(
            model_name='stu_register',
            name='career_goals',
            field=models.TextField(max_length=5000, null=True, verbose_name='What are your current career goals? (Even if you are uncertain/, fill in any thoughts you might have)/,'),
        ),
        migrations.AddField(
            model_name='stu_register',
            name='hopes',
            field=models.TextField(max_length=5000, null=True, verbose_name='What are you hoping for from Career counselling and Guidance Cell?'),
        ),
    ]
