# Generated by Django 4.0.4 on 2022-06-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_stu_register_barries_stu_register_career_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(max_length=5, verbose_name='SI No.')),
                ('date', models.DateField(max_length=50, null=True, verbose_name='Date')),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'offline')], max_length=10, null=True, verbose_name='Mode')),
                ('audience', models.CharField(max_length=100, null=True, verbose_name='Target Audience')),
                ('num_stus', models.IntegerField(null=True, verbose_name='No. Students Reg.')),
                ('speaker', models.CharField(max_length=500, null=True, verbose_name='Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFormFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor_name', models.CharField(max_length=100, null=True, verbose_name='Counselor Name')),
                ('type_of_counselling_session', models.CharField(choices=[('Drop-In', 'Drop-In'), ('Scheduled', 'Scheduled')], max_length=30, verbose_name='Type of counselling session')),
                ('beneficial', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='The meeting was beneficial in achieving my immediate goal (s)')),
                ('Information', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Information was thoroughly and clearly explained.')),
                ('address_my_concerns', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='There was enough time to address my concerns.')),
                ('valuable', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='The session will be valuable to me in completing my academic, career and/or personal goals')),
                ('genuine_interest', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Counselor showed genuine interest in assisting me.')),
                ('knowledgeable', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Counselor was knowledgeable and prepared for the session')),
                ('examine_my_alternatives', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Counselor helped me to consider options and examine my alternatives')),
                ('like', models.TextField(default=None, max_length=500, verbose_name='What did you like about this counselling session?')),
                ('dislike', models.TextField(default=None, max_length=500, verbose_name='What did you dislike about this counselling session?')),
                ('changes', models.TextField(default=None, max_length=500, verbose_name='What specific changes could improve the counselling session?')),
            ],
        ),
        migrations.AlterField(
            model_name='stu_register',
            name='ambition',
            field=models.TextField(max_length=1500, null=True, verbose_name='Ambition'),
        ),
        migrations.AlterField(
            model_name='stu_register',
            name='hobbies',
            field=models.TextField(max_length=500, null=True, verbose_name='hobbies'),
        ),
    ]
