# Generated by Django 4.0.4 on 2022-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_events_feedbackformfields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=500, null=True, verbose_name='Event Name'),
        ),
    ]
