# Generated by Django 4.0.4 on 2022-06-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_events_event_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
