# Generated by Django 4.0.4 on 2022-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='school',
            field=models.CharField(max_length=200, null=True, verbose_name='School'),
        ),
    ]
