# Generated by Django 4.0.4 on 2022-06-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_event_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eve_id',
            field=models.IntegerField(null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='s_no',
            field=models.IntegerField(null=True, verbose_name='SI No.'),
        ),
    ]
