# Generated by Django 4.0.4 on 2022-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_event_eve_id_alter_event_s_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Acadamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='Roll Number')),
                ('section', models.CharField(max_length=20, verbose_name='Section')),
                ('semester', models.CharField(max_length=20, null=True, verbose_name='Semester')),
                ('university_mail_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='University Mail Id')),
                ('course', models.CharField(max_length=50, null=True, verbose_name='Course')),
                ('school', models.CharField(choices=[('None', 'None'), ('School Of Engineering', 'School Of Engineering'), ('School Of Law', 'School Of Law'), ('School Of Desiging', 'School Of Desiging'), ('School Of Management', 'School Of Management')], default='None', max_length=100, verbose_name='School')),
            ],
        ),
        migrations.CreateModel(
            name='Stu_career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambition', models.TextField(max_length=1500, null=True, verbose_name='Ambition')),
                ('hobbies', models.TextField(max_length=500, null=True, verbose_name='hobbies')),
                ('why_ccagc', models.CharField(choices=[('None', 'None'), ('Placements', 'Placements'), ('Higher Studies', 'Higher Studies'), ('Enterpreneurship', 'Enterpreneurship'), ('Other', 'Other')], default='None', max_length=50, verbose_name='You are looking Career counselling and Guidance for')),
                ('career_goals', models.TextField(max_length=5000, null=True, verbose_name='What are your current career goals? (Even if you are uncertain/, fill in any thoughts you might have)/,')),
                ('hopes', models.TextField(max_length=5000, null=True, verbose_name='What are you hoping for from Career counselling and Guidance Cell?')),
                ('barries', models.TextField(max_length=5000, null=True, verbose_name='What kinds of barriers do you think could get in the way of you pursuing the career you want, or meeting your career goals?')),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='None', max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(max_length=20, null=True, verbose_name='Date Of Birth')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.DeleteModel(
            name='Stu_Register',
        ),
    ]
