# Generated by Django 4.0.4 on 2022-06-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_stu_acadamic_stu_career_stu_personal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_personal',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
