# Generated by Django 4.0.4 on 2022-06-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_stu_personal_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_acadamic',
            name='university_mail_id',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Mail Id'),
        ),
    ]
