# Generated by Django 4.0.4 on 2022-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_stu_acadamic_university_mail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFormFieldsPartOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor_name', models.CharField(max_length=100, null=True, verbose_name='Counselor Name')),
                ('type_of_counselling_session', models.CharField(choices=[('Drop-In', 'Drop-In'), ('Scheduled', 'Scheduled')], max_length=30, verbose_name='Type of counselling session')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFormFieldsPartthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.TextField(default=None, max_length=500, verbose_name='What did you like about this counselling session?')),
                ('dislike', models.TextField(default=None, max_length=500, verbose_name='What did you dislike about this counselling session?')),
                ('changes', models.TextField(default=None, max_length=500, verbose_name='What specific changes could improve the counselling session?')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackFormFieldsParttwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficial', models.BooleanField(default=False, verbose_name='The meeting was beneficial in achieving my immediate goal (s)')),
                ('Information', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Information was thoroughly and clearly explained.')),
                ('address_my_concerns', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='There was enough time to address my concerns.')),
                ('valuable', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='The session will be valuable to me in completing my academic, career and/or personal goals')),
                ('genuine_interest', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Counselor showed genuine interest in assisting me.')),
                ('knowledgeable', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Counselor was knowledgeable and prepared for the session')),
                ('examine_my_alternatives', models.BooleanField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], verbose_name='Counselor helped me to consider options and examine my alternatives')),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackFormFields',
        ),
    ]
