# Generated by Django 4.0.4 on 2022-06-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_feedbackformfieldspartone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackformfieldsparttwo',
            name='beneficial',
            field=models.BooleanField(verbose_name='The meeting was beneficial in achieving my immediate goal (s)'),
        ),
    ]
