# Generated by Django 4.0.4 on 2022-06-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_feedbackformfieldsparttwo_beneficial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_personal',
            name='gender',
        ),
    ]
