# Generated by Django 4.0.4 on 2022-06-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_stu_personal_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackformfieldsparttwo',
            name='beneficial',
        ),
    ]
