# Generated by Django 4.0.4 on 2022-06-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_feedbackformfieldsparttwo_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackformfieldspartone',
            name='type_of_counselling_session',
        ),
    ]
